---
# YAML file for DIA servers iLO service
- hosts: all
  vars:
    ilo_user: ilo_user
    ilo_pass: ****
    login_name: newname
    new_uname: newname
    new_pass: ****
  connection: local
  gather_facts: False

  tasks:
     - name: add iLO user account
       add_user_module:
         dia_ilo_inventory_name: "{{ inventory_hostname }}"
         dia_ilo_ip: "{{ ilo_ip }}"
         dia_ilo_user: "{{ ilo_user }}"
         dia_ilo_pass: "{{ ilo_pass }}"
         new_iLO_logname: "{{ login_name }}"
         new_iLO_uname: "{{ new_uname }}"
         new_iLO_passwd: "{{ new_pass }}"
